name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up HTML file with API Key
      run: |
        sed -i "s/YOUR_API_KEY/${{ secrets.GPT3_API_KEY }}/g" index.html
        # The above line replaces YOUR_API_KEY with the secret value
      env:
        GPT3_API_KEY: ${{ secrets.GPT3_API_KEY }}

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p ./public
        cp index.html ./public/
        echo "Deployed on: ${{ github.run_number }}" > ./public/deployment_info.txt
        npx serve ./public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
